Add optional discord username field
NillerMedDild/.github pull request #12
Opened 2022-07-19 13:07 UTC by Quezler

It is a little bit annoying when an issue isn't clear enough and you'd have to ask further questions, and their username doesn't match with any `@member` in the discord the only option is to go back & forth on discord, which spams `#github` & the inboxes of anyone who has notifications on.

I suggest adding an optional field where people can preemptively leave their discord username so they can be contacted outside of the issue comments.

One example of many where it would have been nice: <https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5097>
![Screen Shot 2022-07-19 at 15 05 47](https://user-images.githubusercontent.com/3179271/179757174-0b01b18f-e284-4eca-a674-305c392a886c.png)

2022-07-19 17:26 UTC, NielsPilgaard requested changes

2022-07-19 17:26 UTC, NielsPilgaard commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: textarea
Please use `input` to make the field small :)

2022-07-19 17:26 UTC, NielsPilgaard commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: If you are in the [enigmatica discord](https://discord.com/invite/enigmatica) and wouldn't mind being asked further questions there, leave your username here.
Uppercase `Enigmatica` and `Discord` please :D

2022-07-19 17:26 UTC, NielsPilgaard commented
Comments aside, good idea 👍

2022-07-19 17:30 UTC, Quezler commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: If you are in the [enigmatica discord](https://discord.com/invite/enigmatica) and wouldn't mind being asked further questions there, leave your username here.
ah, the rest of the form seemed to favour lowercase, i shall update it

2022-07-19 17:31 UTC, Quezler commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +  - type: textarea
curse github for not having a form preview mode

2022-07-19 18:59 UTC, NielsPilgaard approved these changes
Lovely commit name 😄

2022-07-19 18:59 UTC, merged

2022-07-19 19:37 UTC, Quezler commented
> Comments aside, good idea 👍

for the record: did you meant the two review "comments", or the 4 console.log "comments" left in the code?

2022-07-20 16:38 UTC, NielsPilgaard commented
Review comments :)